#!/bin/sh
# указываем адреса нужных списков, формируем из двух источников
wget -N https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
wget -N https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
wget -N https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/anudeepND_blacklist_ad_server/master/domains.list
wget -N https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt
wget -N https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
# извлекаем домены из списка hosts
cat hosts | grep '^0\.0\.0\.0' | awk '{print $2}' > block
# извлекаем домены из списка adservers.txt
cat adservers.txt | grep '^0\.0\.0\.0' | awk '{print $2}' > mybase
# извлекаем домены из списка CoinMiner.txt
cat CoinMiner.txt | grep '^0\.0\.0\.0' | awk '{print $2}' > coinminer
# сливаем два списка block и mybase в merged с сортировкой доменов по алфавиту
cat block domains.list mybase coinminer /etc/unbound/myblacklist | sort -u > merged
# сливаем два списка whitelist.txt и mywhitelist в whitelist с сортировкой доменов по алфавиту
cat whitelist.txt /etc/unbound/mywhitelist | sort -u > whitelist
# удаляем из merged домены белого списка whitelist
comm -23 merged whitelist > merged_corr
# удаляем старый список при обновлении
rm /etc/unbound/unbound.conf.d/hosts-alternates.conf 
# создаем список и добавляем "server:" в начало
echo "server:" > /etc/unbound/unbound.conf.d/hosts-alternates.conf
# формируем список вида local_zone: "domain" always_nxdomain
awk '{print "local-zone: \""$1"\" always_nxdomain"}' merged_corr >> /etc/unbound/unbound.conf.d/hosts-alternates.conf
# перезапускаем unbound
systemctl restart unbound
